import 'server-only';

import { resolveSlotCategoryId } from '@/config/merchandising-slots';
import type { DataSource } from '@/lib/data-source/types';

import { getMagentoClient } from './client';
import { mapCategories, mapCmsBlocks, mapProducts, mapStoreConfig } from './mappers';
import {
  EditorialBlocksDocument,
  MerchandisingProductsDocument,
  NavigationCategoriesDocument,
  StoreConfigDocument,
} from './operations';

/**
 * Magento GraphQL implementation of the backend-agnostic `DataSource`
 * interface. Uses `graphql-request` server-side with the `TypedDocumentNode`s
 * generated by `@graphql-codegen` from the committed `schema.graphql`
 * snapshot, and the pure mapping functions in `./mappers`.
 *
 * `import 'server-only'` guarantees this module — and the whole `magento/`
 * connector package it pulls in — can never be bundled into client code,
 * preserving the server-only trust boundary. It is imported by exactly ONE
 * module: the DataSource resolution layer at `../index.ts` (architectural
 * rule: all backend access goes through the DataSource interface), enforced
 * by the adapter-import restriction check.
 */

function notNull<T>(value: T): value is NonNullable<T> {
  return value != null;
}

export const magentoGraphQLAdapter: DataSource = {
  async getStoreConfig({ storeCode }) {
    const client = getMagentoClient({ storeCode });
    const data = await client.request(StoreConfigDocument);
    return mapStoreConfig(data.storeConfig ?? {});
  },

  async getNavigationCategories({ storeCode, currency, rootCategoryId }) {
    const client = getMagentoClient({ storeCode, currency });
    const data = await client.request(NavigationCategoriesDocument, {
      // DataSource arg is `rootCategoryId: number`; Magento's filter `eq` is String.
      rootCategoryId: String(rootCategoryId),
    });
    const categories = (data.categoryList ?? []).filter(notNull);
    return mapCategories(categories);
  },

  async getProductsByMerchandisingSlot({ storeCode, currency, slot, limit }) {
    const client = getMagentoClient({ storeCode, currency });
    const data = await client.request(MerchandisingProductsDocument, {
      categoryId: resolveSlotCategoryId(slot),
      pageSize: limit,
    });
    const items = (data.products?.items ?? []).filter(notNull);
    return mapProducts(items);
  },

  async getEditorialContent({ storeCode, identifiers }) {
    const client = getMagentoClient({ storeCode });
    const data = await client.request(EditorialBlocksDocument, { identifiers });
    const items = (data.cmsBlocks?.items ?? []).filter(notNull);
    return mapCmsBlocks(items);
  },
};
