import 'server-only';

import { cacheLife, cacheTag } from 'next/cache';

import { resolveSlotCategoryId } from '@/config/merchandising-slots';
import { STORE_IDENTITY_CONTENT_IDENTIFIERS } from '@/config/store-identity-content';
import type { CmsBlock, DataSource, StoreConfig } from '@/lib/data-source/types';

import { getMagentoClient } from './client';
import {
  composeStoreIdentity,
  mapCategories,
  mapCmsBlocks,
  mapNewsletterStatus,
  mapProducts,
  mapStoreConfig,
} from './mappers';
import {
  EditorialBlocksDocument,
  MerchandisingProductsDocument,
  NavigationCategoriesDocument,
  StoreConfigDocument,
  SubscribeNewsletterDocument,
} from './operations';

/**
 * Magento GraphQL implementation of the backend-agnostic `DataSource`
 * interface. Uses `graphql-request` server-side with the `TypedDocumentNode`s
 * generated by `@graphql-codegen` from the committed `schema.graphql`
 * snapshot, and the pure mapping functions in `./mappers`.
 *
 * `import 'server-only'` guarantees this module — and the whole `magento/`
 * connector package it pulls in — can never be bundled into client code,
 * preserving the server-only trust boundary. It is imported by exactly ONE
 * module: the DataSource resolution layer at `../index.ts` (architectural
 * rule: all backend access goes through the DataSource interface), enforced
 * by the adapter-import restriction check.
 */

function notNull<T>(value: T): value is NonNullable<T> {
  return value != null;
}

export const magentoGraphQLAdapter: DataSource = {
  async getStoreConfig({ storeCode }) {
    const client = getMagentoClient({ storeCode });
    const data = await client.request(StoreConfigDocument);
    return mapStoreConfig(data.storeConfig ?? {});
  },

  async getStoreIdentity({ storeCode }) {
    'use cache';
    // Cache key is Store (`storeCode`) only — `Content-Currency` is
    // intentionally omitted. Every field this read returns (name, logo, legal
    // fields, tagline, payment badges, footer columns, delivery copy) is
    // currency-invariant: none carries a price or any currency-dependent value,
    // so the same store view yields identical identity regardless of display
    // currency and a currency-scoped key would only fragment the cache. This
    // invariance is the precondition for the store-only key: if a future
    // price/currency-varying field is ever added to this read, `Content-Currency`
    // has to be reinstated in the key (and passed to `getMagentoClient` below).
    cacheTag('store-identity');
    // 1h safety window (the built-in 'hours' profile: stale 5min / revalidate
    // 1h / expire 1day — no custom profile is defined in next.config.ts, so
    // this named profile is the project's existing convention for a
    // non-default window). This is the ZERO-COUPLING baseline: it bounds
    // worst-case staleness with no Magento-side trigger required at all. The
    // on-demand `POST /api/revalidate` endpoint (`revalidateTag('store-identity')`)
    // is the OPTIONAL fast path — when an operator wires any authed trigger at
    // it, edits surface immediately and this window never gets a chance to
    // matter; when none is wired, this 1h window is what actually bounds
    // staleness.
    cacheLife('hours');

    const client = getMagentoClient({ storeCode });

    // Each source is fetched independently and any transport failure is
    // contained here: an unreachable source degrades to an empty config/block
    // set rather than leaking a raw backend error, so the fail-closed check in
    // `composeStoreIdentity` uniformly handles "unreachable" and "missing
    // value" as the same outcome (and logs the same field-naming marker).
    let storeConfig: StoreConfig;
    try {
      const data = await client.request(StoreConfigDocument);
      storeConfig = mapStoreConfig(data.storeConfig ?? {});
    } catch {
      storeConfig = mapStoreConfig({});
    }

    let blocks: CmsBlock[];
    try {
      const data = await client.request(EditorialBlocksDocument, {
        identifiers: STORE_IDENTITY_CONTENT_IDENTIFIERS,
      });
      blocks = mapCmsBlocks((data.cmsBlocks?.items ?? []).filter(notNull));
    } catch {
      blocks = [];
    }

    return composeStoreIdentity({ storeConfig, blocks });
  },

  async getNavigationCategories({ storeCode, currency, rootCategoryId }) {
    const client = getMagentoClient({ storeCode, currency });
    const data = await client.request(NavigationCategoriesDocument, {
      // DataSource arg is `rootCategoryId: number`; Magento's filter `eq` is String.
      rootCategoryId: String(rootCategoryId),
    });
    const categories = (data.categoryList ?? []).filter(notNull);
    return mapCategories(categories);
  },

  async getProductsByMerchandisingSlot({ storeCode, currency, slot, limit }) {
    const client = getMagentoClient({ storeCode, currency });
    const data = await client.request(MerchandisingProductsDocument, {
      categoryId: resolveSlotCategoryId(slot),
      pageSize: limit,
    });
    const items = (data.products?.items ?? []).filter(notNull);
    return mapProducts(items);
  },

  async getEditorialContent({ storeCode, identifiers }) {
    const client = getMagentoClient({ storeCode });
    const data = await client.request(EditorialBlocksDocument, { identifiers });
    const items = (data.cmsBlocks?.items ?? []).filter(notNull);
    return mapCmsBlocks(items);
  },

  async subscribeToNewsletter({ storeCode, currency, email }) {
    // `Store` + `Content-Currency` are set explicitly on the outbound request,
    // like every other scope-bound backend call.
    const client = getMagentoClient({ storeCode, currency });
    try {
      const data = await client.request(SubscribeNewsletterDocument, { email });
      return { status: mapNewsletterStatus(data.subscribeEmailToNewsletter?.status) };
    } catch {
      // Trust-boundary containment: swallow the raw backend/transport error so
      // no backend URL, header, or error text can reach the caller. The caller
      // only ever sees the neutral `{ status: 'error' }` outcome.
      return { status: 'error' };
    }
  },
};
