import 'server-only';

import { ClientError } from 'graphql-request';
import { cacheLife, cacheTag } from 'next/cache';

import { resolveSlotCategoryId } from '@/config/merchandising-slots';
import { STORE_IDENTITY_CONTENT_IDENTIFIERS } from '@/config/store-identity-content';
import type { EditorialBlocksQuery } from '@/gql/graphql';
import type {
  CmsBlock,
  DataSource,
  StoreConfig,
  StoreIdentity,
} from '@/lib/data-source/types';

import { getMagentoClient } from './client';
import {
  composeStoreIdentity,
  mapCategories,
  mapCmsBlocks,
  mapNewsletterStatus,
  mapProducts,
  mapStoreConfig,
} from './mappers';
import {
  EditorialBlocksDocument,
  MerchandisingProductsDocument,
  NavigationCategoriesDocument,
  StoreConfigDocument,
  SubscribeNewsletterDocument,
} from './operations';

/**
 * Magento GraphQL implementation of the backend-agnostic `DataSource`
 * interface. Uses `graphql-request` server-side with the `TypedDocumentNode`s
 * generated by `@graphql-codegen` from the committed `schema.graphql`
 * snapshot, and the pure mapping functions in `./mappers`.
 *
 * `import 'server-only'` guarantees this module — and the whole `magento/`
 * connector package it pulls in — can never be bundled into client code,
 * preserving the server-only trust boundary. It is imported by exactly ONE
 * module: the DataSource resolution layer at `../index.ts` (architectural
 * rule: all backend access goes through the DataSource interface), enforced
 * by the adapter-import restriction check.
 */

function notNull<T>(value: T): value is NonNullable<T> {
  return value != null;
}

/**
 * Fetch CMS blocks by identifier with partial-error recovery.
 *
 * Magento returns a per-identifier GraphQL error for any identifier with no
 * matching CMS block — the EXPECTED shape for an optional/not-yet-authored
 * identifier (e.g. a home zone a merchant hasn't set up yet, or the alcohol
 * legal notice before it's authored; see `store-identity-content.ts` /
 * `content-zones.ts` for which identifiers are optional vs required by their
 * respective callers). `graphql-request` throws a `ClientError` on ANY
 * top-level `errors` entry even though its `response.data` still carries
 * every OTHER identifier that WAS found. Recovering that partial `data` here
 * is what stops ONE missing identifier from taking down every OTHER
 * identifier in the same batched request — shared by `loadStoreIdentity`
 * (identity content) and `getEditorialContent` (home/header editorial
 * zones), both of which batch multiple identifiers in one call. A genuine
 * transport failure (the endpoint unreachable, no data at all, or any other
 * non-`ClientError`) still degrades to `[]`, unchanged from before this
 * function existed.
 */
async function fetchEditorialBlocksResilient(
  client: ReturnType<typeof getMagentoClient>,
  identifiers: string[],
): Promise<CmsBlock[]> {
  try {
    const data = await client.request(EditorialBlocksDocument, { identifiers });
    return mapCmsBlocks((data.cmsBlocks?.items ?? []).filter(notNull));
  } catch (err) {
    const partialItems =
      err instanceof ClientError
        ? (err.response.data as EditorialBlocksQuery | undefined)?.cmsBlocks?.items
        : undefined;
    return partialItems ? mapCmsBlocks(partialItems.filter(notNull)) : [];
  }
}

/**
 * The cached store-identity read. Extracted to a MODULE-LEVEL `async function`
 * deliberately: Next's `'use cache'` compiler transform applies to file-level
 * and top-level function declarations, NOT to object-method shorthand. When the
 * directive lived inside `magentoGraphQLAdapter.getStoreIdentity` (a method) it
 * was a silent no-op — the read never cached, so `cacheTag`/`cacheLife` had no
 * effect and on-demand `revalidateTag('store-identity')` could never bound or
 * flip staleness (an edit surfaced on the very next request regardless). This
 * mirrors the working `getHomeShellData` cached read in `@/lib/home/home-data`.
 * The adapter method below is a thin delegator so the DataSource surface is
 * unchanged.
 */
export async function loadStoreIdentity({
  storeCode,
}: {
  storeCode: string;
}): Promise<StoreIdentity> {
  'use cache';
  // Cache key is Store (`storeCode`) only — `Content-Currency` is
  // intentionally omitted. Every field this read returns (name, logo, legal
  // fields, tagline, payment badges, footer columns, delivery copy) is
  // currency-invariant: none carries a price or any currency-dependent value,
  // so the same store view yields identical identity regardless of display
  // currency and a currency-scoped key would only fragment the cache. This
  // invariance is the precondition for the store-only key: if a future
  // price/currency-varying field is ever added to this read, `Content-Currency`
  // has to be reinstated in the key (and passed to `getMagentoClient` below).
  cacheTag('store-identity');
  // 1h safety window (the built-in 'hours' profile: stale 5min / revalidate
  // 1h / expire 1day — no custom profile is defined in next.config.ts, so
  // this named profile is the project's existing convention for a
  // non-default window). This is the ZERO-COUPLING baseline: it bounds
  // worst-case staleness with no Magento-side trigger required at all. The
  // on-demand `POST /api/revalidate` endpoint (`revalidateTag('store-identity')`)
  // is the OPTIONAL fast path — when an operator wires any authed trigger at
  // it, edits surface immediately and this window never gets a chance to
  // matter; when none is wired, this 1h window is what actually bounds
  // staleness.
  cacheLife('hours');

  const client = getMagentoClient({ storeCode });

  // Each source is fetched independently and any transport failure is
  // contained here: an unreachable source degrades to an empty config/block
  // set rather than leaking a raw backend error, so the fail-closed check in
  // `composeStoreIdentity` uniformly handles "unreachable" and "missing
  // value" as the same outcome (and logs the same field-naming marker).
  let storeConfig: StoreConfig;
  try {
    const data = await client.request(StoreConfigDocument);
    storeConfig = mapStoreConfig(data.storeConfig ?? {});
  } catch {
    storeConfig = mapStoreConfig({});
  }

  // Partial-error recovery (see `fetchEditorialBlocksResilient` above): one
  // unauthored OPTIONAL identity field (e.g. the alcohol legal notice before
  // it's set up) must never cascade into a fail-closed throw for an
  // UNRELATED REQUIRED field (registrationNumber) that resolved just fine —
  // treating a partial not-found the same as a total outage would be MORE
  // fail-closed than the design calls for, not less.
  const blocks = await fetchEditorialBlocksResilient(
    client,
    STORE_IDENTITY_CONTENT_IDENTIFIERS,
  );

  return composeStoreIdentity({ storeConfig, blocks });
}

export const magentoGraphQLAdapter: DataSource = {
  async getStoreConfig({ storeCode }) {
    const client = getMagentoClient({ storeCode });
    const data = await client.request(StoreConfigDocument);
    return mapStoreConfig(data.storeConfig ?? {});
  },

  // Thin delegator to the module-level cached `loadStoreIdentity`. The
  // `'use cache'` directive MUST live on that top-level function, not here — a
  // directive inside this method shorthand is not transformed by Next and would
  // silently disable caching (and with it, on-demand revalidation).
  async getStoreIdentity({ storeCode }) {
    return loadStoreIdentity({ storeCode });
  },

  async getNavigationCategories({ storeCode, currency, rootCategoryId }) {
    const client = getMagentoClient({ storeCode, currency });
    const data = await client.request(NavigationCategoriesDocument, {
      // DataSource arg is `rootCategoryId: number`; Magento's filter `eq` is String.
      rootCategoryId: String(rootCategoryId),
    });
    const categories = (data.categoryList ?? []).filter(notNull);
    return mapCategories(categories);
  },

  async getProductsByMerchandisingSlot({ storeCode, currency, slot, limit }) {
    const client = getMagentoClient({ storeCode, currency });
    const data = await client.request(MerchandisingProductsDocument, {
      categoryId: resolveSlotCategoryId(slot),
      pageSize: limit,
    });
    const items = (data.products?.items ?? []).filter(notNull);
    return mapProducts(items);
  },

  async getEditorialContent({ storeCode, identifiers }) {
    const client = getMagentoClient({ storeCode });
    // Partial-error recovery (see `fetchEditorialBlocksResilient` above): a
    // single unauthored/misconfigured identifier among several requested in
    // one batch (e.g. a home zone, or the header mega-menu promo block) must
    // not take down every OTHER identifier's content — that would turn one
    // missing optional zone into a hard-failed home/header render.
    return fetchEditorialBlocksResilient(client, identifiers);
  },

  async subscribeToNewsletter({ storeCode, currency, email }) {
    // `Store` + `Content-Currency` are set explicitly on the outbound request,
    // like every other scope-bound backend call.
    const client = getMagentoClient({ storeCode, currency });
    try {
      const data = await client.request(SubscribeNewsletterDocument, { email });
      return { status: mapNewsletterStatus(data.subscribeEmailToNewsletter?.status) };
    } catch {
      // Trust-boundary containment: swallow the raw backend/transport error so
      // no backend URL, header, or error text can reach the caller. The caller
      // only ever sees the neutral `{ status: 'error' }` outcome.
      return { status: 'error' };
    }
  },
};
